### ISSUE TITLE
Tomcat don't save new password

### ISSUE THREAD

**Issue by minya92** [altsoft/PlatypusJS#93]
I'm trying to change the password in the tomcat server settings, but nothing happens, password remains the same.
Username change without problems.

![image](https://cloud.githubusercontent.com/assets/4252803/17018414/492a2310-4f40-11e6-8e0c-fb82d23d78fc.png)

**Comment by hcspidergrasp** [comment]
I dont know about MustDieOS, but in Linux things like this happens when designer is not allowed to read and write user configuration. In default installation in Linux this configuration contains in `~/.platypusdesigner` folder. It also includes Apache Tomcat global configurations and application contexts.
I think your configuration allocated in `C:\Users\lapsh\AppData\Roaming\.platypusdesigner` according to your screenshot. Go there and find `tomcat-users.xml`, you can change username and password there.
